### ISSUE TITLE
Can I still use TW Rest API with Bob plugin?

### ISSUE THREAD

**Issue by linonetwo** [OokTech/TW5-Bob#145] opened 2020-07-23 16:47 UTC
Some plugin like https://github.com/sobjornstad/TiddlyRemember rely on TiddlyWiki REST API,
can I still query TW REST API?

I'd like my app to support them with Bob enabled.

**Comment by linonetwo** [comment] 2020-07-23 16:58
Seems `http://localhost:5012/recipes/default/tiddlers.json` is not working anymore.

**Comment by inmysocks** [comment] 2020-07-24 08:23
Did that ever work with Bob?

A long time ago I made a rest api that could do that but it was in the external server, never in the Bob plugin

**Comment by linonetwo** [comment] 2020-07-24 13:18
So maybe I have to start a SimpleServer manually. I will look into code and try that.

Do you think starting another SimpleServer will cause any problem? Will CRUD from that SimpleServer cause trouble for Bob ws server?

**Comment by inmysocks** [comment] 2020-07-26 07:17
I do not know how the simple server will interact with the wsserver, but your fix for the file system monitor should mean it isn't a big problem.

The problem is that the SimpleServer api can only work with one wiki.
Bob has fetching functions for the server that can handle Bobs structure, the routes are:

- https://github.com/OokTech/TW5-Bob/blob/master/ServerRoutes/post-fetch-list.js - returns a filtered list of titles from a wiki
- https://github.com/OokTech/TW5-Bob/blob/master/ServerRoutes/post-fetch.js - use a filter to fetch tiddlers from a wiki
- https://github.com/OokTech/TW5-Bob/blob/master/ServerRoutes/post-plugin-list.js - list the plugins available in the servers plugin library
- https://github.com/OokTech/TW5-Bob/blob/master/ServerRoutes/post-fetch-plugin.js - fetch a plugin from the servers plugin library

If those routes don't do what you need I think that a much better idea would be to just write new routes that do instead of using the simple server and hoping there aren't problems.

**Comment by inmysocks** [comment] 2020-10-14 07:18
I updated and documented the http api in version 1.6.2. There are problems with the documentation but it should be usable so I am closing this.

If there are more problems or specific things missing please make a new issue so I can track them easier.

**Closed** 2020-10-14 07:33 UTC
Labels: Documentation Needed, Feature Request

**Comment by linonetwo** [comment] 2021-04-01 11:49
Seems API is slightly different？

https://github.com/OokTech/TW5-Bob/blob/master/Documentation/HTTPAPI/get-tiddlers-fetch.tid
and https://tiddlywiki.com/#WebServer%20API%3A%20Get%20Tiddler
