### ISSUE TITLE
Drag and Drop $:/Import does not work while running Bob

### ISSUE THREAD

**Issue by joshuafontany** [OokTech/TW5-Bob#119] opened 2020-01-14 22:32 UTC
I have tested this with just a bare-bones wiki, and am not able to complete any $:/Import operation. I may have some incorrect Settings, as I have traced this to:
**$:/plugins/OokTech/Bob/BrowserWSAdaptor.js**

```
$tw.hooks.addHook("th-importing-tiddler", function (tiddler) {
if ($tw.settings.saveMediaOnServer === 'yes' && $tw.settings.enableFileServer === 'yes') {
```

Both of those variables are undefined and thus the fuction returns undefined and the file (img, text file, etc) is not imported. The link generated opens a "missing tiddler".
    
Thanks,
Joshua F
---

I am running (check any that apply, put an x inside the [ ] to check a box, like this: [x]):

- [x] Windows
- [ ] OSX
- [ ] Linux
- [ ] Other

and using

- [x] The nodejs version
- [ ] The single file executable

Before posting I read [issue guidelines](./IssueGuidelines.md) and:

- [x] I am using the newest version
- [x] The answer to my question isn't listed in the documentation or this isn't
  a question
- [x] This is not a duplicate issue
- [x] I have not done anything that required me to set acceptance to
  `I Will Not Get Tech Support For This`

**Comment by joshuafontany** [comment] 2020-01-15 21:34
Debugging a bit, the settings are being loaded correctly from disk on the server end, but are not there in the browser once the Wiki is loaded. This is what the watch on `$tw.settings` shows from in Chrome once the wiki is loaded. It is mostly empty, but does the the heartbeat data...

$tw.settings: Object
wikis: {}
advanced: {}
heartbeat:
    interval: 1000
    timeout: 5000
    TTLID: 697

Changing the line above in BrowserWSAdaptor.js to ` if (true) {` worked as a temporary fix.

**Comment by inmysocks** [comment] 2020-02-08 08:46
Thank you for the bug report, I can see where the problem is and I need to think a bit about how to fix it.

The problem is that the settings don't always get sent to a wiki for privacy and access control reasons with the secure version of Bob we are working on and I expect there to be other issues like this that pop up.
The next release is going to require a lot of testing because of issues like this.

**Comment by inmysocks** [comment] 2020-03-26 20:12
This should be fixed in the next release of Bob.

**Closed by inmysocks** 2020-03-26 20:12 UTC
